-- Themes
require("core.plugin_configs.themes")

-- Plugins
require("core.plugin_configs.animate")
require("core.plugin_configs.autoSessions")
require("core.plugin_configs.bufferline")
require("core.plugin_configs.calltree")
require("core.plugin_configs.codeium")
require("core.plugin_configs.difftree")
require("core.plugin_configs.easy-commands")
require("core.plugin_configs.fugitive")
require("core.plugin_configs.gitsigns")
require("core.plugin_configs.ibl")
require("core.plugin_configs.lazygit")
require("core.plugin_configs.lsp")
require("core.plugin_configs.lualine")
require("core.plugin_configs.metals")
require("core.plugin_configs.mini_statusline")
require("core.plugin_configs.notify")
require("core.plugin_configs.nvimtree")
require("core.plugin_configs.oil")
require("core.plugin_configs.peek")
require("core.plugin_configs.spider")
require("core.plugin_configs.sttusline")
require("core.plugin_configs.swagger")
require("core.plugin_configs.telescope")
require("core.plugin_configs.toggleterm")
require("core.plugin_configs.treesitter")
require("core.plugin_configs.undotree")
require("core.plugin_configs.venn")
require("core.plugin_configs.whichKey")
