-- Plugins
require("core.plugin_configs.bufferline")
require("core.plugin_configs.colorscheme")
require("core.plugin_configs.fugitive")
require("core.plugin_configs.gitsigns")
require("core.plugin_configs.lazygit")
require("core.plugin_configs.lsp")
require("core.plugin_configs.lualine")
require("core.plugin_configs.metals")
require("core.plugin_configs.notify")
require("core.plugin_configs.nvimtree")
require("core.plugin_configs.oil")
require("core.plugin_configs.ollama")
require("core.plugin_configs.telescope")
require("core.plugin_configs.toggleterm")
require("core.plugin_configs.treesitter")
require("core.plugin_configs.undotree")

-- Nvim Settings
require("core.settings")
